//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RemotePotatoServer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowExpert {
            get {
                return ((bool)(this["ShowExpert"]));
            }
            set {
                this["ShowExpert"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9080")]
        public decimal Port {
            get {
                return ((decimal)(this["Port"]));
            }
            set {
                this["Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugServer {
            get {
                return ((bool)(this["DebugServer"]));
            }
            set {
                this["DebugServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RequirePassword {
            get {
                return ((bool)(this["RequirePassword"]));
            }
            set {
                this["RequirePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserPassword {
            get {
                return ((string)(this["UserPassword"]));
            }
            set {
                this["UserPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShownMinimiseTooltip {
            get {
                return ((bool)(this["ShownMinimiseTooltip"]));
            }
            set {
                this["ShownMinimiseTooltip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal DefaultPrePadding {
            get {
                return ((decimal)(this["DefaultPrePadding"]));
            }
            set {
                this["DefaultPrePadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public decimal DefaultPostPadding {
            get {
                return ((decimal)(this["DefaultPostPadding"]));
            }
            set {
                this["DefaultPostPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("240")]
        public decimal DefaultSearchSpan {
            get {
                return ((decimal)(this["DefaultSearchSpan"]));
            }
            set {
                this["DefaultSearchSpan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableEPG {
            get {
                return ((bool)(this["EnableEPG"]));
            }
            set {
                this["EnableEPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("My Media Center")]
        public string MainMenuTitle {
            get {
                return ((string)(this["MainMenuTitle"]));
            }
            set {
                this["MainMenuTitle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Remote Manual Recording")]
        public string DefaultManualRecordingName {
            get {
                return ((string)(this["DefaultManualRecordingName"]));
            }
            set {
                this["DefaultManualRecordingName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public decimal EPGGridChannelsPerPage {
            get {
                return ((decimal)(this["EPGGridChannelsPerPage"]));
            }
            set {
                this["EPGGridChannelsPerPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("grid")]
        public string CurrentEPGType {
            get {
                return ((string)(this["CurrentEPGType"]));
            }
            set {
                this["CurrentEPGType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFavouriteChannelsInEPG {
            get {
                return ((bool)(this["ShowFavouriteChannelsInEPG"]));
            }
            set {
                this["ShowFavouriteChannelsInEPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShownWindowsSearchWarning {
            get {
                return ((bool)(this["ShownWindowsSearchWarning"]));
            }
            set {
                this["ShownWindowsSearchWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CacheBinaryFiles {
            get {
                return ((bool)(this["CacheBinaryFiles"]));
            }
            set {
                this["CacheBinaryFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CacheTextFiles {
            get {
                return ((bool)(this["CacheTextFiles"]));
            }
            set {
                this["CacheTextFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugCache {
            get {
                return ((bool)(this["DebugCache"]));
            }
            set {
                this["DebugCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugAdvanced {
            get {
                return ((bool)(this["DebugAdvanced"]));
            }
            set {
                this["DebugAdvanced"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default")]
        public string CurrentMainThemeName {
            get {
                return ((string)(this["CurrentMainThemeName"]));
            }
            set {
                this["CurrentMainThemeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("minimalist")]
        public string CurrentMobileThemeName {
            get {
                return ((string)(this["CurrentMobileThemeName"]));
            }
            set {
                this["CurrentMobileThemeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugBasic {
            get {
                return ((bool)(this["DebugBasic"]));
            }
            set {
                this["DebugBasic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>iPhone</string>
  <string>BlackBerry</string>
  <string>Palm</string>
  <string>PPC</string>
  <string>IEMobile</string>
  <string>Android</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MobileUserAgents {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MobileUserAgents"]));
            }
            set {
                this["MobileUserAgents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentUserAgents {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentUserAgents"]));
            }
            set {
                this["RecentUserAgents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ForcedAboutTab {
            get {
                return ((bool)(this["ForcedAboutTab"]));
            }
            set {
                this["ForcedAboutTab"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowChannelLogos {
            get {
                return ((bool)(this["ShowChannelLogos"]));
            }
            set {
                this["ShowChannelLogos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180")]
        public int EPGTimespanMinutes {
            get {
                return ((int)(this["EPGTimespanMinutes"]));
            }
            set {
                this["EPGTimespanMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public decimal ViewScheduledRecordingsDaysAhead {
            get {
                return ((decimal)(this["ViewScheduledRecordingsDaysAhead"]));
            }
            set {
                this["ViewScheduledRecordingsDaysAhead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TreatAllProgrammesAsSeries {
            get {
                return ((bool)(this["TreatAllProgrammesAsSeries"]));
            }
            set {
                this["TreatAllProgrammesAsSeries"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBackgroundColoursInEPG {
            get {
                return ((bool)(this["ShowBackgroundColoursInEPG"]));
            }
            set {
                this["ShowBackgroundColoursInEPG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEPGRecordingDots {
            get {
                return ((bool)(this["ShowEPGRecordingDots"]));
            }
            set {
                this["ShowEPGRecordingDots"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public decimal EPGGridPreviewWindowSize {
            get {
                return ((decimal)(this["EPGGridPreviewWindowSize"]));
            }
            set {
                this["EPGGridPreviewWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsUpgradeRequired {
            get {
                return ((bool)(this["SettingsUpgradeRequired"]));
            }
            set {
                this["SettingsUpgradeRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7")]
        public int RecommendedMovieMinimumRating {
            get {
                return ((int)(this["RecommendedMovieMinimumRating"]));
            }
            set {
                this["RecommendedMovieMinimumRating"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEPGRecommendedMovies {
            get {
                return ((bool)(this["ShowEPGRecommendedMovies"]));
            }
            set {
                this["ShowEPGRecommendedMovies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ListMoviesOnFavouriteChannelsOnly {
            get {
                return ((bool)(this["ListMoviesOnFavouriteChannelsOnly"]));
            }
            set {
                this["ListMoviesOnFavouriteChannelsOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastCheckedForAppUpdates {
            get {
                return ((global::System.DateTime)(this["LastCheckedForAppUpdates"]));
            }
            set {
                this["LastCheckedForAppUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal DaysBetweenAppUpdateCheck {
            get {
                return ((decimal)(this["DaysBetweenAppUpdateCheck"]));
            }
            set {
                this["DaysBetweenAppUpdateCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForAppUpdates {
            get {
                return ((bool)(this["CheckForAppUpdates"]));
            }
            set {
                this["CheckForAppUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EPGShowChannelNumbers {
            get {
                return ((bool)(this["EPGShowChannelNumbers"]));
            }
            set {
                this["EPGShowChannelNumbers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SilverlightEnabled {
            get {
                return ((bool)(this["SilverlightEnabled"]));
            }
            set {
                this["SilverlightEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SilverlightIsDefault {
            get {
                return ((bool)(this["SilverlightIsDefault"]));
            }
            set {
                this["SilverlightIsDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9081")]
        public decimal SilverlightStreamingPort {
            get {
                return ((decimal)(this["SilverlightStreamingPort"]));
            }
            set {
                this["SilverlightStreamingPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SilverlightStreamingQuality {
            get {
                return ((int)(this["SilverlightStreamingQuality"]));
            }
            set {
                this["SilverlightStreamingQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int StreamPackMinimumBuildRequired {
            get {
                return ((int)(this["StreamPackMinimumBuildRequired"]));
            }
            set {
                this["StreamPackMinimumBuildRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugStreaming {
            get {
                return ((bool)(this["DebugStreaming"]));
            }
            set {
                this["DebugStreaming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserName {
            get {
                return ((string)(this["UserName"]));
            }
            set {
                this["UserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120")]
        public int AuthSessionTimeoutMinutes {
            get {
                return ((int)(this["AuthSessionTimeoutMinutes"]));
            }
            set {
                this["AuthSessionTimeoutMinutes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastUpdateInfoShownForMajVersion {
            get {
                return ((int)(this["LastUpdateInfoShownForMajVersion"]));
            }
            set {
                this["LastUpdateInfoShownForMajVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastUpdateInfoShownForMinVersion {
            get {
                return ((int)(this["LastUpdateInfoShownForMinVersion"]));
            }
            set {
                this["LastUpdateInfoShownForMinVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IsTechPreview {
            get {
                return ((bool)(this["IsTechPreview"]));
            }
            set {
                this["IsTechPreview"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoneVeryFirstChannelListSort {
            get {
                return ((bool)(this["DoneVeryFirstChannelListSort"]));
            }
            set {
                this["DoneVeryFirstChannelListSort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportInternetTVChannels {
            get {
                return ((bool)(this["ImportInternetTVChannels"]));
            }
            set {
                this["ImportInternetTVChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImportHiddenTVChannels {
            get {
                return ((bool)(this["ImportHiddenTVChannels"]));
            }
            set {
                this["ImportHiddenTVChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecordingsRetrieveAsParanoid {
            get {
                return ((bool)(this["RecordingsRetrieveAsParanoid"]));
            }
            set {
                this["RecordingsRetrieveAsParanoid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugScheduling {
            get {
                return ((bool)(this["DebugScheduling"]));
            }
            set {
                this["DebugScheduling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowRemoteLogRetrieval {
            get {
                return ((bool)(this["AllowRemoteLogRetrieval"]));
            }
            set {
                this["AllowRemoteLogRetrieval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal SilverlightEPGOverspillHours {
            get {
                return ((decimal)(this["SilverlightEPGOverspillHours"]));
            }
            set {
                this["SilverlightEPGOverspillHours"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BlockChannelsUserHidden {
            get {
                return ((bool)(this["BlockChannelsUserHidden"]));
            }
            set {
                this["BlockChannelsUserHidden"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockChannelsUserAdded {
            get {
                return ((bool)(this["BlockChannelsUserAdded"]));
            }
            set {
                this["BlockChannelsUserAdded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockChannelsUserMapped {
            get {
                return ((bool)(this["BlockChannelsUserMapped"]));
            }
            set {
                this["BlockChannelsUserMapped"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BlockChannelsUnknown {
            get {
                return ((bool)(this["BlockChannelsUnknown"]));
            }
            set {
                this["BlockChannelsUnknown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugChannels {
            get {
                return ((bool)(this["DebugChannels"]));
            }
            set {
                this["DebugChannels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastSetSecurityForPort {
            get {
                return ((int)(this["LastSetSecurityForPort"]));
            }
            set {
                this["LastSetSecurityForPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HaveOfferedWindowsFirewallForPort {
            get {
                return ((int)(this["HaveOfferedWindowsFirewallForPort"]));
            }
            set {
                this["HaveOfferedWindowsFirewallForPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HaveAddedFirewallRuleForMainPort {
            get {
                return ((int)(this["HaveAddedFirewallRuleForMainPort"]));
            }
            set {
                this["HaveAddedFirewallRuleForMainPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SilverlightCacheEPGDays {
            get {
                return ((bool)(this["SilverlightCacheEPGDays"]));
            }
            set {
                this["SilverlightCacheEPGDays"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShownServiceRunsInBackgroundWarning {
            get {
                return ((bool)(this["ShownServiceRunsInBackgroundWarning"]));
            }
            set {
                this["ShownServiceRunsInBackgroundWarning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultKeepUntil {
            get {
                return ((int)(this["DefaultKeepUntil"]));
            }
            set {
                this["DefaultKeepUntil"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultQuality {
            get {
                return ((int)(this["DefaultQuality"]));
            }
            set {
                this["DefaultQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int DefaultKeepNumberOfEpisodes {
            get {
                return ((int)(this["DefaultKeepNumberOfEpisodes"]));
            }
            set {
                this["DefaultKeepNumberOfEpisodes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PadResponseWithExtraBytes {
            get {
                return ((bool)(this["PadResponseWithExtraBytes"]));
            }
            set {
                this["PadResponseWithExtraBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12000")]
        public int CacheBinaryFileMaxLengthBytes {
            get {
                return ((int)(this["CacheBinaryFileMaxLengthBytes"]));
            }
            set {
                this["CacheBinaryFileMaxLengthBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>C:\\</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection RecordedTVFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecordedTVFolders"]));
            }
            set {
                this["RecordedTVFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SilverlightStoreCacheLocally {
            get {
                return ((bool)(this["SilverlightStoreCacheLocally"]));
            }
            set {
                this["SilverlightStoreCacheLocally"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugRecTV {
            get {
                return ((bool)(this["DebugRecTV"]));
            }
            set {
                this["DebugRecTV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int MediaStreamerSecondsToKeepAlive {
            get {
                return ((int)(this["MediaStreamerSecondsToKeepAlive"]));
            }
            set {
                this["MediaStreamerSecondsToKeepAlive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnforceClientIPSecurity {
            get {
                return ((bool)(this["EnforceClientIPSecurity"]));
            }
            set {
                this["EnforceClientIPSecurity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RecurseRecTVSubfolders {
            get {
                return ((bool)(this["RecurseRecTVSubfolders"]));
            }
            set {
                this["RecurseRecTVSubfolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MediaStreamerUseExtraAudioSync {
            get {
                return ((bool)(this["MediaStreamerUseExtraAudioSync"]));
            }
            set {
                this["MediaStreamerUseExtraAudioSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int RecTVRecheckPostponedFilesEvery {
            get {
                return ((int)(this["RecTVRecheckPostponedFilesEvery"]));
            }
            set {
                this["RecTVRecheckPostponedFilesEvery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugFullAPI {
            get {
                return ((bool)(this["DebugFullAPI"]));
            }
            set {
                this["DebugFullAPI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MusicLibraryIndexingEverDone {
            get {
                return ((bool)(this["MusicLibraryIndexingEverDone"]));
            }
            set {
                this["MusicLibraryIndexingEverDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime MusicLibraryIndexingLastDone {
            get {
                return ((global::System.DateTime)(this["MusicLibraryIndexingLastDone"]));
            }
            set {
                this["MusicLibraryIndexingLastDone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MergeLineUps {
            get {
                return ((bool)(this["MergeLineUps"]));
            }
            set {
                this["MergeLineUps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseUPNPRouter {
            get {
                return ((bool)(this["UseUPNPRouter"]));
            }
            set {
                this["UseUPNPRouter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HaveAskedWhetherToUseUPNPRouter {
            get {
                return ((bool)(this["HaveAskedWhetherToUseUPNPRouter"]));
            }
            set {
                this["HaveAskedWhetherToUseUPNPRouter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugUPNPRouter {
            get {
                return ((bool)(this["DebugUPNPRouter"]));
            }
            set {
                this["DebugUPNPRouter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPublicIP {
            get {
                return ((string)(this["LastPublicIP"]));
            }
            set {
                this["LastPublicIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime LastGotPublicIP {
            get {
                return ((global::System.DateTime)(this["LastGotPublicIP"]));
            }
            set {
                this["LastGotPublicIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("test.dyndns.org")]
        public string DynamicDNSHostname {
            get {
                return ((string)(this["DynamicDNSHostname"]));
            }
            set {
                this["DynamicDNSHostname"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DynDNSUsername {
            get {
                return ((string)(this["DynDNSUsername"]));
            }
            set {
                this["DynDNSUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DynDNSPassword {
            get {
                return ((string)(this["DynDNSPassword"]));
            }
            set {
                this["DynDNSPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DynDNSClientEnabled {
            get {
                return ((bool)(this["DynDNSClientEnabled"]));
            }
            set {
                this["DynDNSClientEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DynamicDNSServiceUsed {
            get {
                return ((bool)(this["DynamicDNSServiceUsed"]));
            }
            set {
                this["DynamicDNSServiceUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EverShownSetupWizard {
            get {
                return ((bool)(this["EverShownSetupWizard"]));
            }
            set {
                this["EverShownSetupWizard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int SilverlightStreamingNumberOfPorts {
            get {
                return ((int)(this["SilverlightStreamingNumberOfPorts"]));
            }
            set {
                this["SilverlightStreamingNumberOfPorts"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SendInput")]
        public string SendKeys {
            get {
                return ((string)(this["SendKeys"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HaveEverSetRPKeySenderToStartWithWindows {
            get {
                return ((bool)(this["HaveEverSetRPKeySenderToStartWithWindows"]));
            }
            set {
                this["HaveEverSetRPKeySenderToStartWithWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DeinterlaceRecTVByDefault {
            get {
                return ((bool)(this["DeinterlaceRecTVByDefault"]));
            }
            set {
                this["DeinterlaceRecTVByDefault"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>bmp</string>
  <string>gif</string>
  <string>jpg</string>
  <string>jpeg</string>
  <string>tiff</string>
  <string>tif</string>
  <string>png</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ImageFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ImageFileExtensions"]));
            }
            set {
                this["ImageFileExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>avi</string>
  <string>mpeg</string>
  <string>flv</string>
  <string>mov</string>
  <string>mp4</string>
  <string>wmv</string>
  <string>wtv</string>
  <string>dvr-ms</string>
  <string>m4v</string>
  <string>3gp</string>
  <string>m2ts</string>
  <string>mpg</string>
  <string>m2v</string>
  <string>ts</string>
  <string>vob</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VideoFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VideoFileExtensions"]));
            }
            set {
                this["VideoFileExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>mp3</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection MusicFileExtensions {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["MusicFileExtensions"]));
            }
            set {
                this["MusicFileExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableMediaCenterSupport {
            get {
                return ((bool)(this["EnableMediaCenterSupport"]));
            }
            set {
                this["EnableMediaCenterSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HaveDoneVanillaSetup {
            get {
                return ((bool)(this["HaveDoneVanillaSetup"]));
            }
            set {
                this["HaveDoneVanillaSetup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableMusicLibrary {
            get {
                return ((bool)(this["EnableMusicLibrary"]));
            }
            set {
                this["EnableMusicLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnablePictureLibrary {
            get {
                return ((bool)(this["EnablePictureLibrary"]));
            }
            set {
                this["EnablePictureLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>C:\\</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection VideoLibraryFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["VideoLibraryFolders"]));
            }
            set {
                this["VideoLibraryFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>C:\\</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PictureLibraryFolders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PictureLibraryFolders"]));
            }
            set {
                this["PictureLibraryFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseExplorerLibraryForPictureFolders {
            get {
                return ((bool)(this["UseExplorerLibraryForPictureFolders"]));
            }
            set {
                this["UseExplorerLibraryForPictureFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseExplorerLibraryForVideoFolders {
            get {
                return ((bool)(this["UseExplorerLibraryForVideoFolders"]));
            }
            set {
                this["UseExplorerLibraryForVideoFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableVideoLibrary {
            get {
                return ((bool)(this["EnableVideoLibrary"]));
            }
            set {
                this["EnableVideoLibrary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowExpertTabsInUI {
            get {
                return ((bool)(this["ShowExpertTabsInUI"]));
            }
            set {
                this["ShowExpertTabsInUI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugAdvancedStreaming {
            get {
                return ((bool)(this["DebugAdvancedStreaming"]));
            }
            set {
                this["DebugAdvancedStreaming"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HaveEverNagged {
            get {
                return ((bool)(this["HaveEverNagged"]));
            }
            set {
                this["HaveEverNagged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2010-01-01")]
        public global::System.DateTime DateLastNagged {
            get {
                return ((global::System.DateTime)(this["DateLastNagged"]));
            }
            set {
                this["DateLastNagged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool HaveVisitedDonatePage {
            get {
                return ((bool)(this["HaveVisitedDonatePage"]));
            }
            set {
                this["HaveVisitedDonatePage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DefaultRecordFirstRunOnly {
            get {
                return ((bool)(this["DefaultRecordFirstRunOnly"]));
            }
            set {
                this["DefaultRecordFirstRunOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultSeriesRequestSubtype {
            get {
                return ((int)(this["DefaultSeriesRequestSubtype"]));
            }
            set {
                this["DefaultSeriesRequestSubtype"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RestrictMediaStreamerToLevel30 {
            get {
                return ((bool)(this["RestrictMediaStreamerToLevel30"]));
            }
            set {
                this["RestrictMediaStreamerToLevel30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CustomFFMpegTemplate {
            get {
                return ((string)(this["CustomFFMpegTemplate"]));
            }
            set {
                this["CustomFFMpegTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseCustomFFMpegTemplate {
            get {
                return ((bool)(this["UseCustomFFMpegTemplate"]));
            }
            set {
                this["UseCustomFFMpegTemplate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("110")]
        public decimal StreamingVolumePercent {
            get {
                return ((decimal)(this["StreamingVolumePercent"]));
            }
            set {
                this["StreamingVolumePercent"] = value;
            }
        }
    }
}
